const CLEAR_LOCAL_STORAGE = 'CLEAR_LOCAL_STORAGE';
const APP_INIT_DONE = 'APP_INIT_DONE';

const MENU_SELECT = 'MENU_SELECT';
const OPEN_MOBILE_SELECT = 'OPEN_MOBILE_SELECT';
const CLOSE_MOBILE_SELECT = 'CLOSE_MOBILE_SELECT';

export {
    CLEAR_LOCAL_STORAGE,
    APP_INIT_DONE,

    MENU_SELECT,
    OPEN_MOBILE_SELECT,
    CLOSE_MOBILE_SELECT
}